### ISSUE TITLE
Problem with python 

### ISSUE THREAD

**Issue by atfresh279** [kayaen/Finger_Classification#1]
Hello, whenever I run the record python script it gives me this error message
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\atfre\Downloads\Finger_Classification-master\Finger_Classification-master\data_record.py 
Traceback (most recent call last):
  File "C:\Users\atfre\Downloads\Finger_Classification-master\Finger_Classification-master\data_record.py", line 2, in <module>
    from Myo_python.Myo import MyoRaw
  File "C:\Users\atfre\Downloads\Finger_Classification-master\Finger_Classification-master\Myo_python\Myo.py", line 2, in <module>
    from bt import BT
ImportError: No module named 'bt'
>>> 
Please adivise

**Comment by kayaen** [comment]
Hi, 
Fİrstly, I am sorry to late answer. This code is written in Python 2.7 so if you try to run in Python 3 it does not work. You can download the Anaconda Python 2.7 version, then use the Spyder to run the code in Windows.
